"""
Questions for NUQRO – IQ, EQ, SQ, AQ tests
Expanded edition – more variety, dimensions for sub‑scores.

Each question is a dict:
- id: unique identifier
- text: the question
- options: {A: "...", B: "...", C: "...", D: "..."}
- correct: (IQ only) the right answer
- explain: explanation of the answer
- min_age: minimum age to see this question
- scores: (EQ/SQ/AQ) mapping from answer letter to raw points (1-5)
- dimension / factor: (EQ/SQ/AQ) for sub‑score breakdown
"""

import random

# ========================
#  IQ QUESTIONS (30)
# ========================

IQ_QUESTIONS = [
    # Easy
    {
        'id': 'IQ001',
        'text': 'What comes next?  2, 4, 6, 8, ?',
        'options': {'A': '9', 'B': '10', 'C': '11', 'D': '12'},
        'correct': 'B',
        'explain': 'Add 2 each time. Even numbers.',
        'min_age': 8,
    },
    {
        'id': 'IQ002',
        'text': 'A square has 4 sides. How many sides do 3 squares have?',
        'options': {'A': '7', 'B': '12', 'C': '15', 'D': '16'},
        'correct': 'B',
        'explain': '3 × 4 = 12 sides.',
        'min_age': 8,
    },
    {
        'id': 'IQ003',
        'text': 'Cat is to kitten as dog is to __?',
        'options': {'A': 'wolf', 'B': 'puppy', 'C': 'cub', 'D': 'foal'},
        'correct': 'B',
        'explain': 'A puppy is a young dog.',
        'min_age': 10,
    },
    {
        'id': 'IQ004',
        'text': 'All birds have feathers. A penguin is a bird. Does a penguin have feathers?',
        'options': {'A': 'Yes', 'B': 'No', 'C': 'Maybe', 'D': 'Only in water'},
        'correct': 'A',
        'explain': 'Penguin is a bird, so yes.',
        'min_age': 11,
    },
    {
        'id': 'IQ005',
        'text': 'Which word is different? Apple, Banana, Carrot, Orange',
        'options': {'A': 'Apple', 'B': 'Banana', 'C': 'Carrot', 'D': 'Orange'},
        'correct': 'C',
        'explain': 'Carrot is a vegetable; the rest are fruits.',
        'min_age': 9,
    },
    {
        'id': 'IQ006',
        'text': 'If you rearrange "CIFAIPC", you get a:',
        'options': {'A': 'Ocean', 'B': 'City', 'C': 'Animal', 'D': 'Country'},
        'correct': 'A',
        'explain': 'CIFAIPC → PACIFIC (an ocean).',
        'min_age': 10,
    },
    # Medium
    {
        'id': 'IQ007',
        'text': 'A shirt costs $40. It\'s 25% off. What do you pay?',
        'options': {'A': '$30', 'B': '$32', 'C': '$35', 'D': '$38'},
        'correct': 'A',
        'explain': '25% of $40 = $10. $40 - $10 = $30.',
        'min_age': 12,
    },
    {
        'id': 'IQ008',
        'text': 'Which number comes next?  1, 1, 2, 3, 5, 8, ?',
        'options': {'A': '11', 'B': '12', 'C': '13', 'D': '14'},
        'correct': 'C',
        'explain': 'Fibonacci sequence: 5+8=13.',
        'min_age': 13,
    },
    {
        'id': 'IQ009',
        'text': 'EPHEMERAL means:',
        'options': {'A': 'Permanent', 'B': 'Short-lived', 'C': 'Beautiful', 'D': 'Strange'},
        'correct': 'B',
        'explain': 'Ephemeral = lasting a very short time.',
        'min_age': 14,
    },
    {
        'id': 'IQ010',
        'text': 'A car goes 300 km in 5 hours. Average speed?',
        'options': {'A': '50 km/h', 'B': '60 km/h', 'C': '70 km/h', 'D': '80 km/h'},
        'correct': 'B',
        'explain': '300 ÷ 5 = 60 km/h.',
        'min_age': 12,
    },
    {
        'id': 'IQ011',
        'text': 'What is 15% of 240?',
        'options': {'A': '32', 'B': '36', 'C': '40', 'D': '45'},
        'correct': 'B',
        'explain': '10% = 24, 5% = 12, total 36.',
        'min_age': 12,
    },
    {
        'id': 'IQ012',
        'text': 'A man is 4 times as old as his son. In 20 years, he will be twice as old. How old is the son now?',
        'options': {'A': '5', 'B': '10', 'C': '15', 'D': '20'},
        'correct': 'B',
        'explain': 'Let son = x, father = 4x. In 20 years: 4x+20 = 2(x+20) → 4x+20 = 2x+40 → 2x = 20 → x=10.',
        'min_age': 14,
    },
    # Harder
    {
        'id': 'IQ013',
        'text': 'Some roses are red. All red things are beautiful. Which MUST be true?',
        'options': {
            'A': 'All roses are beautiful',
            'B': 'Some roses are beautiful',
            'C': 'Red things are always roses',
            'D': 'Nothing red is ugly',
        },
        'correct': 'B',
        'explain': 'The red roses are beautiful, so at least some roses are beautiful.',
        'min_age': 15,
    },
    {
        'id': 'IQ014',
        'text': 'If today is Wednesday, what day was it 100 days ago?',
        'options': {'A': 'Monday', 'B': 'Tuesday', 'C': 'Wednesday', 'D': 'Thursday'},
        'correct': 'A',
        'explain': '100 ÷ 7 = 14 weeks + 2 days. Back 2 days from Wednesday = Monday.',
        'min_age': 15,
    },
    {
        'id': 'IQ015',
        'text': 'A bat and a ball cost $1.10. The bat costs $1.00 more than the ball. How much is the ball?',
        'options': {'A': '5 cents', 'B': '10 cents', 'C': '15 cents', 'D': '20 cents'},
        'correct': 'A',
        'explain': 'If ball = x, bat = x+1.00, total = 2x+1.00 = 1.10 → 2x = 0.10 → x=0.05 (5 cents).',
        'min_age': 16,
    },
    {
        'id': 'IQ016',
        'text': 'Complete the sequence: 2, 5, 10, 17, ?',
        'options': {'A': '24', 'B': '26', 'C': '28', 'D': '30'},
        'correct': 'B',
        'explain': 'Differences: 3,5,7, next +9 → 26.',
        'min_age': 14,
    },
    {
        'id': 'IQ017',
        'text': 'Which is the odd one out?',
        'options': {'A': 'Circle', 'B': 'Square', 'C': 'Triangle', 'D': 'Pyramid'},
        'correct': 'D',
        'explain': 'Pyramid is 3D; others are 2D shapes.',
        'min_age': 10,
    },
    {
        'id': 'IQ018',
        'text': 'If 2 workers can build a wall in 6 days, how many days will 3 workers take?',
        'options': {'A': '3', 'B': '4', 'C': '5', 'D': '9'},
        'correct': 'B',
        'explain': 'Work = 2*6 = 12 worker-days. 12/3 = 4 days.',
        'min_age': 13,
    },
    {
        'id': 'IQ019',
        'text': 'Which number is missing?  5, 9, 17, 33, ?',
        'options': {'A': '45', 'B': '55', 'C': '65', 'D': '75'},
        'correct': 'C',
        'explain': 'Double and subtract 1: (5*2)-1=9, (9*2)-1=17, (17*2)-1=33, (33*2)-1=65.',
        'min_age': 14,
    },
    {
        'id': 'IQ020',
        'text': 'A dice has 6 faces. How many dots are on opposite faces of a standard die?',
        'options': {'A': '6', 'B': '7', 'C': '8', 'D': '9'},
        'correct': 'B',
        'explain': 'Opposite sides sum to 7.',
        'min_age': 12,
    },
    {
        'id': 'IQ021',
        'text': 'What is the next letter? B, C, E, G, K, ?',
        'options': {'A': 'M', 'B': 'N', 'C': 'P', 'D': 'Q'},
        'correct': 'A',
        'explain': 'Prime-numbered positions: 2nd letter B, 3rd C, 5th E, 7th G, 11th K, next prime 13 → M.',
        'min_age': 15,
    },
    {
        'id': 'IQ022',
        'text': 'A man is looking at a portrait. Someone asks him, "Who are you looking at?" He replies: "Brothers and sisters I have none, but that man’s father is my father’s son." Who is in the portrait?',
        'options': {'A': 'His son', 'B': 'His father', 'C': 'His brother', 'D': 'His uncle'},
        'correct': 'A',
        'explain': '"My father’s son" is himself (since no brothers). So "that man’s father is me" → the man in the portrait is his son.',
        'min_age': 16,
    },
    {
        'id': 'IQ023',
        'text': 'If a clock shows 3:15, what is the angle between hour and minute hands?',
        'options': {'A': '0°', 'B': '7.5°', 'C': '15°', 'D': '22.5°'},
        'correct': 'B',
        'explain': 'At 3:15, minute hand at 3, hour hand 0.25 of way from 3 to 4 → 0.25*30° = 7.5°.',
        'min_age': 14,
    },
    {
        'id': 'IQ024',
        'text': 'Which word is a synonym for "OBFUSCATE"?',
        'options': {'A': 'Clarify', 'B': 'Confuse', 'C': 'Simplify', 'D': 'Illuminate'},
        'correct': 'B',
        'explain': 'Obfuscate means to make unclear or confusing.',
        'min_age': 15,
    },
    {
        'id': 'IQ025',
        'text': 'If 3 cats catch 3 mice in 3 minutes, how many cats catch 100 mice in 100 minutes?',
        'options': {'A': '3', 'B': '9', 'C': '100', 'D': '300'},
        'correct': 'A',
        'explain': '1 cat catches 1 mouse in 3 minutes. In 100 minutes, 1 cat catches 100/3 mice. To catch 100 mice, you need 3 cats (since 3 * 100/3 = 100).',
        'min_age': 13,
    },
    {
        'id': 'IQ026',
        'text': 'What is the smallest positive integer that is divisible by 1,2,3,4,5,6?',
        'options': {'A': '30', 'B': '60', 'C': '120', 'D': '180'},
        'correct': 'B',
        'explain': 'LCM of 1-6 is 60.',
        'min_age': 12,
    },
    {
        'id': 'IQ027',
        'text': 'If you fold a paper in half 3 times and then cut a corner, how many holes will you have?',
        'options': {'A': '1', 'B': '3', 'C': '6', 'D': '8'},
        'correct': 'D',
        'explain': 'Each fold doubles layers: 2^3 = 8 layers, cutting a corner cuts through all 8.',
        'min_age': 12,
    },
    {
        'id': 'IQ028',
        'text': 'What is the next number? 2, 3, 5, 9, 17, ?',
        'options': {'A': '25', 'B': '33', 'C': '35', 'D': '37'},
        'correct': 'B',
        'explain': 'Each term is double previous minus 1: (2*2)-1=3, (3*2)-1=5, (5*2)-1=9, (9*2)-1=17, (17*2)-1=33.',
        'min_age': 13,
    },
    {
        'id': 'IQ029',
        'text': 'Which one is the odd one out?',
        'options': {'A': 'Kangaroo', 'B': 'Koala', 'C': 'Ostrich', 'D': 'Wallaby'},
        'correct': 'C',
        'explain': 'Ostrich is a bird; the others are marsupials.',
        'min_age': 10,
    },
    {
        'id': 'IQ030',
        'text': 'A train travels 60 km in 40 minutes. What is its speed in km/h?',
        'options': {'A': '80', 'B': '90', 'C': '100', 'D': '120'},
        'correct': 'B',
        'explain': '40 minutes = 2/3 hour. Speed = 60 / (2/3) = 60 * 3/2 = 90 km/h.',
        'min_age': 12,
    },
]

# ========================
#  EQ QUESTIONS (20)
# ========================

EQ_QUESTIONS = [
    {
        'id': 'EQ001',
        'text': 'When you feel angry, what do you do FIRST?',
        'options': {
            'A': 'Yell or act without thinking',
            'B': 'Try to understand WHY I\'m angry',
            'C': 'Ignore it and move on',
            'D': 'Talk to someone about it',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 4},
        'dimension': 'self_management',
        'explain': 'High EQ: understand your emotions before reacting.',
        'min_age': 10,
    },
    {
        'id': 'EQ002',
        'text': 'A friend is crying but says "I\'m fine." What do you do?',
        'options': {
            'A': 'Believe them and change the subject',
            'B': 'Gently ask if they want to talk',
            'C': 'Tell them to stop crying',
            'D': 'Walk away',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 3},
        'dimension': 'social_awareness',
        'explain': 'High EQ means reading past words and creating safe space.',
        'min_age': 10,
    },
    {
        'id': 'EQ003',
        'text': 'Your boss criticizes your work unfairly in front of others. You:',
        'options': {
            'A': 'Argue back immediately',
            'B': 'Stay calm, listen, talk to them privately later',
            'C': 'Shut down and say nothing for days',
            'D': 'Complain to coworkers',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 2},
        'dimension': 'self_management',
        'explain': 'High EQ: manage your reaction AND address the issue appropriately.',
        'min_age': 14,
    },
    {
        'id': 'EQ004',
        'text': 'During a conflict with someone you care about, you:',
        'options': {
            'A': 'Focus on winning',
            'B': 'Seek to understand their perspective first',
            'C': 'Avoid the conflict',
            'D': 'Get others to take your side',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 2},
        'dimension': 'relationship_management',
        'explain': 'High EQ in conflict = curiosity about the other person.',
        'min_age': 13,
    },
    {
        'id': 'EQ005',
        'text': 'After a big failure, how do you typically respond?',
        'options': {
            'A': 'Blame external factors',
            'B': 'Analyse what went wrong and plan differently',
            'C': 'Give up on that goal',
            'D': 'Pretend it didn\'t matter',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'self_awareness',
        'explain': 'High EQ: use failure as information, not identity.',
        'min_age': 14,
    },
    {
        'id': 'EQ006',
        'text': 'A colleague seems stressed but hasn\'t said anything. You:',
        'options': {
            'A': 'Mind your own business',
            'B': 'Check in: "You seem off, everything OK?"',
            'C': 'Tell others you think they\'re stressed',
            'D': 'Wait for them to ask for help',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 3},
        'dimension': 'social_awareness',
        'explain': 'Proactive but not intrusive empathy = high EQ.',
        'min_age': 15,
    },
    {
        'id': 'EQ007',
        'text': 'You made a mistake that hurt someone. You:',
        'options': {
            'A': 'Apologize sincerely and try to make amends',
            'B': 'Avoid the person for a while',
            'C': 'Make excuses for why it happened',
            'D': 'Blame them for being too sensitive',
        },
        'scores': {'A': 5, 'B': 2, 'C': 1, 'D': 1},
        'dimension': 'relationship_management',
        'explain': 'Ownership of mistakes repairs trust.',
        'min_age': 12,
    },
    {
        'id': 'EQ008',
        'text': 'How often do you know exactly why you feel a certain way?',
        'options': {
            'A': 'Rarely',
            'B': 'Sometimes',
            'C': 'Often',
            'D': 'Almost always',
        },
        'scores': {'A': 1, 'B': 2, 'C': 4, 'D': 5},
        'dimension': 'self_awareness',
        'explain': 'Emotional granularity is a sign of high EQ.',
        'min_age': 12,
    },
    {
        'id': 'EQ009',
        'text': 'When someone shares good news, you typically:',
        'options': {
            'A': 'Say "congrats" and move on',
            'B': 'Ask excited questions about it',
            'C': 'Change the subject',
            'D': 'Feel jealous inside',
        },
        'scores': {'A': 3, 'B': 5, 'C': 1, 'D': 1},
        'dimension': 'relationship_management',
        'explain': 'Active constructive responding strengthens bonds.',
        'min_age': 12,
    },
    {
        'id': 'EQ010',
        'text': 'You feel anxious before a presentation. You:',
        'options': {
            'A': 'Tell yourself "just stop being nervous"',
            'B': 'Breathe deeply and reframe it as excitement',
            'C': 'Avoid presenting if possible',
            'D': 'Drink caffeine to calm down',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'self_management',
        'explain': 'Regulating anxiety is a core EQ skill.',
        'min_age': 14,
    },
    {
        'id': 'EQ011',
        'text': 'A friend is being bullied. You:',
        'options': {
            'A': 'Stand up for them directly',
            'B': 'Support them privately after',
            'C': 'Stay out of it to avoid trouble',
            'D': 'Tell a trusted adult',
        },
        'scores': {'A': 5, 'B': 4, 'C': 1, 'D': 3},
        'dimension': 'social_awareness',
        'explain': 'Empathy in action is courageous.',
        'min_age': 11,
    },
    {
        'id': 'EQ012',
        'text': 'You receive negative feedback. Your first thought is:',
        'options': {
            'A': 'This person is wrong',
            'B': 'What can I learn?',
            'C': 'I feel attacked',
            'D': 'I already knew that',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 2},
        'dimension': 'self_awareness',
        'explain': 'Growth mindset = high EQ.',
        'min_age': 13,
    },
    # New EQ questions
    {
        'id': 'EQ013',
        'text': 'Your partner/spouse is upset about something unrelated to you. You:',
        'options': {
            'A': 'Try to solve their problem',
            'B': 'Listen and validate their feelings',
            'C': 'Give them space',
            'D': 'Tell them to cheer up',
        },
        'scores': {'A': 3, 'B': 5, 'C': 4, 'D': 1},
        'dimension': 'relationship_management',
        'explain': 'Often people just need empathy, not solutions.',
        'min_age': 16,
    },
    {
        'id': 'EQ014',
        'text': 'You see a stranger fall down in public. You:',
        'options': {
            'A': 'Look away to avoid embarrassment',
            'B': 'Ask if they are okay',
            'C': 'Laugh quietly',
            'D': 'Wait for someone else to help',
        },
        'scores': {'A': 1, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'social_awareness',
        'explain': 'Empathy means helping even when it\'s awkward.',
        'min_age': 10,
    },
    {
        'id': 'EQ015',
        'text': 'You’ve had a terrible day. When you get home, you:',
        'options': {
            'A': 'Snap at family members',
            'B': 'Tell them you need a few minutes to decompress',
            'C': 'Bottle it up and pretend nothing is wrong',
            'D': 'Drink alcohol to relax',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 1},
        'dimension': 'self_management',
        'explain': 'Healthy self-management means communicating needs, not dumping emotions.',
        'min_age': 14,
    },
    {
        'id': 'EQ016',
        'text': 'Your team is divided on a decision. You:',
        'options': {
            'A': 'Push for your view strongly',
            'B': 'Mediate and find common ground',
            'C': 'Stay silent to avoid conflict',
            'D': 'Side with the majority',
        },
        'scores': {'A': 2, 'B': 5, 'C': 2, 'D': 3},
        'dimension': 'relationship_management',
        'explain': 'High EQ seeks integration, not division.',
        'min_age': 15,
    },
    {
        'id': 'EQ017',
        'text': 'When you’re overwhelmed, you typically:',
        'options': {
            'A': 'Keep pushing through',
            'B': 'Take a break and breathe',
            'C': 'Complain to everyone',
            'D': 'Shut down completely',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 1},
        'dimension': 'self_management',
        'explain': 'Recognizing overwhelm and regulating is key.',
        'min_age': 12,
    },
    {
        'id': 'EQ018',
        'text': 'A coworker takes credit for your work. You:',
        'options': {
            'A': 'Confront them publicly',
            'B': 'Speak to them privately and calmly',
            'C': 'Do nothing, avoid conflict',
            'D': 'Sabotage their future work',
        },
        'scores': {'A': 2, 'B': 5, 'C': 2, 'D': 1},
        'dimension': 'self_management',
        'explain': 'Assertive, not aggressive.',
        'min_age': 15,
    },
    {
        'id': 'EQ019',
        'text': 'You notice a friend is withdrawing. You:',
        'options': {
            'A': 'Assume they\'re mad at you',
            'B': 'Reach out and ask how they are',
            'C': 'Give them space indefinitely',
            'D': 'Talk about them to others',
        },
        'scores': {'A': 2, 'B': 5, 'C': 3, 'D': 1},
        'dimension': 'social_awareness',
        'explain': 'Proactive checking in shows empathy.',
        'min_age': 12,
    },
    {
        'id': 'EQ020',
        'text': 'After a heated argument, you usually:',
        'options': {
            'A': 'Hold a grudge',
            'B': 'Try to repair the relationship quickly',
            'C': 'Wait for the other to apologise first',
            'D': 'Forget it ever happened',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 3},
        'dimension': 'relationship_management',
        'explain': 'High EQ actively repairs ruptures.',
        'min_age': 13,
    },
]

# ========================
#  SQ QUESTIONS (20)
# ========================

SQ_QUESTIONS = [
    {
        'id': 'SQ001',
        'text': 'At a group event, you notice someone standing alone. You:',
        'options': {
            'A': 'Focus on your own conversations',
            'B': 'Walk over and introduce yourself',
            'C': 'Ask a friend to help them',
            'D': 'Make eye contact and smile',
        },
        'scores': {'A': 1, 'B': 5, 'C': 3, 'D': 4},
        'factor': 'social_acting',
        'explain': 'High SQ: read the room and include others.',
        'min_age': 11,
    },
    {
        'id': 'SQ002',
        'text': 'While someone tells a story, you:',
        'options': {
            'A': 'Nod and wait for your turn',
            'B': 'Interrupt with your own thought',
            'C': 'Ask clarifying questions',
            'D': 'Check your phone briefly',
        },
        'scores': {'A': 3, 'B': 2, 'C': 5, 'D': 1},
        'factor': 'social_relating',
        'explain': 'Active listening = asking questions, not just nodding.',
        'min_age': 12,
    },
    {
        'id': 'SQ003',
        'text': 'You want to change someone\'s opinion. You:',
        'options': {
            'A': 'Present facts until they agree',
            'B': 'Acknowledge their view, then share yours',
            'C': 'Get others to pressure them',
            'D': 'Drop it - people never change',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 1},
        'factor': 'social_cognising',
        'explain': 'Validate first, then open the door with questions.',
        'min_age': 14,
    },
    {
        'id': 'SQ004',
        'text': 'Someone says "That\'s great" but crosses their arms and looks away. You:',
        'options': {
            'A': 'Take their words at face value',
            'B': 'Notice the mismatch and follow up later',
            'C': 'Call it out immediately',
            'D': 'Assume they don\'t like you',
        },
        'scores': {'A': 2, 'B': 5, 'C': 2, 'D': 1},
        'factor': 'social_cognising',
        'explain': 'Reading body language is key SQ skill.',
        'min_age': 13,
    },
    {
        'id': 'SQ005',
        'text': 'A classmate is being left out of a game. You:',
        'options': {
            'A': 'Ignore it',
            'B': 'Invite them to join',
            'C': 'Ask the group why they excluded them',
            'D': 'Tell a teacher',
        },
        'scores': {'A': 1, 'B': 5, 'C': 4, 'D': 3},
        'factor': 'social_acting',
        'explain': 'Direct inclusion is the highest-SQ response.',
        'min_age': 10,
    },
    {
        'id': 'SQ006',
        'text': 'When meeting someone new, your focus is:',
        'options': {
            'A': 'What I do and what I need',
            'B': 'Learning about them and finding connection',
            'C': 'Collecting their contact info',
            'D': 'Making a memorable impression',
        },
        'scores': {'A': 2, 'B': 5, 'C': 3, 'D': 3},
        'factor': 'social_relating',
        'explain': 'Real networking is curiosity-led, not extraction-led.',
        'min_age': 15,
    },
    {
        'id': 'SQ007',
        'text': 'In a group project, someone dominates the conversation. You:',
        'options': {
            'A': 'Stay quiet to avoid conflict',
            'B': 'Interrupt and redirect the floor',
            'C': 'Privately suggest everyone gets a turn',
            'D': 'Let them finish, then speak',
        },
        'scores': {'A': 2, 'B': 3, 'C': 5, 'D': 4},
        'factor': 'social_acting',
        'explain': 'High SQ: handle group dynamics tactfully.',
        'min_age': 14,
    },
    {
        'id': 'SQ008',
        'text': 'You accidentally hurt a friend\'s feelings. You:',
        'options': {
            'A': 'Apologise and ask how to make it right',
            'B': 'Explain it was a joke',
            'C': 'Wait for them to get over it',
            'D': 'Avoid them for a while',
        },
        'scores': {'A': 5, 'B': 2, 'C': 1, 'D': 1},
        'factor': 'social_relating',
        'explain': 'Repair attempts build trust.',
        'min_age': 11,
    },
    {
        'id': 'SQ009',
        'text': 'You sense tension between two friends. You:',
        'options': {
            'A': 'Stay neutral and don\'t get involved',
            'B': 'Try to mediate if both want help',
            'C': 'Pick a side',
            'D': 'Spread gossip about it',
        },
        'scores': {'A': 3, 'B': 5, 'C': 1, 'D': 1},
        'factor': 'social_cognising',
        'explain': 'High SQ: offer help without taking sides.',
        'min_age': 14,
    },
    {
        'id': 'SQ010',
        'text': 'When someone tells a joke you don\'t understand, you:',
        'options': {
            'A': 'Laugh anyway',
            'B': 'Ask them to explain it',
            'C': 'Ignore it',
            'D': 'Make a different joke',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 2},
        'factor': 'social_acting',
        'explain': 'Honest curiosity is better than fake politeness.',
        'min_age': 12,
    },
    {
        'id': 'SQ011',
        'text': 'Your friend is upset about something you did. You:',
        'options': {
            'A': 'Say "I\'m sorry you feel that way"',
            'B': 'Say "I\'m sorry I hurt you, I was wrong"',
            'C': 'Explain why you did it',
            'D': 'Tell them to calm down',
        },
        'scores': {'A': 2, 'B': 5, 'C': 3, 'D': 1},
        'factor': 'social_relating',
        'explain': 'A full apology validates feelings and takes responsibility.',
        'min_age': 12,
    },
    {
        'id': 'SQ012',
        'text': 'At a party, you don\'t know anyone. You:',
        'options': {
            'A': 'Find a corner and use your phone',
            'B': 'Look for someone who also seems alone and introduce yourself',
            'C': 'Leave early',
            'D': 'Wait to be approached',
        },
        'scores': {'A': 1, 'B': 5, 'C': 1, 'D': 2},
        'factor': 'social_acting',
        'explain': 'Initiating contact is a core social skill.',
        'min_age': 13,
    },
    # New SQ questions
    {
        'id': 'SQ013',
        'text': 'You’re in a disagreement with a coworker. You:',
        'options': {
            'A': 'Repeat your point louder',
            'B': 'Summarize their view to show you understand',
            'C': 'Walk away',
            'D': 'Get a manager involved',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 3},
        'factor': 'social_cognising',
        'explain': 'Paraphrasing builds rapport and de-escalates.',
        'min_age': 14,
    },
    {
        'id': 'SQ014',
        'text': 'A friend is going through a tough time. You:',
        'options': {
            'A': 'Give advice even if not asked',
            'B': 'Listen and ask what they need',
            'C': 'Share your own similar story',
            'D': 'Avoid the topic',
        },
        'scores': {'A': 2, 'B': 5, 'C': 3, 'D': 1},
        'factor': 'social_relating',
        'explain': 'Ask what support looks like to them.',
        'min_age': 12,
    },
    {
        'id': 'SQ015',
        'text': 'You’re introduced to someone you don’t like. You:',
        'options': {
            'A': 'Are polite but distant',
            'B': 'Show genuine interest anyway',
            'C': 'Ignore them',
            'D': 'Make a sarcastic comment',
        },
        'scores': {'A': 4, 'B': 5, 'C': 1, 'D': 1},
        'factor': 'social_acting',
        'explain': 'Professional courtesy is a social skill.',
        'min_age': 13,
    },
    {
        'id': 'SQ016',
        'text': 'You’re in a noisy room and can’t hear someone. You:',
        'options': {
            'A': 'Nod and pretend you heard',
            'B': 'Ask them to repeat or move somewhere quieter',
            'C': 'Ignore them',
            'D': 'Shout over the noise',
        },
        'scores': {'A': 1, 'B': 5, 'C': 1, 'D': 2},
        'factor': 'social_acting',
        'explain': 'Asking for clarity shows respect.',
        'min_age': 11,
    },
    {
        'id': 'SQ017',
        'text': 'Someone keeps interrupting you. You:',
        'options': {
            'A': 'Stop talking',
            'B': 'Politely say "I’d like to finish my point"',
            'C': 'Interrupt them back',
            'D': 'Talk louder',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 2},
        'factor': 'social_acting',
        'explain': 'Assertive communication is key.',
        'min_age': 13,
    },
    {
        'id': 'SQ018',
        'text': 'You’re at a networking event. You:',
        'options': {
            'A': 'Wait to be approached',
            'B': 'Approach others with an open question',
            'C': 'Stick with people you know',
            'D': 'Talk about your achievements first',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 2},
        'factor': 'social_acting',
        'explain': 'Initiating with curiosity is high SQ.',
        'min_age': 15,
    },
    {
        'id': 'SQ019',
        'text': 'You accidentally say something offensive. You:',
        'options': {
            'A': 'Defend your intent',
            'B': 'Apologise without excuses',
            'C': 'Ignore it',
            'D': 'Blame the listener for being sensitive',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 1},
        'factor': 'social_relating',
        'explain': 'Own the impact, not just intent.',
        'min_age': 13,
    },
    {
        'id': 'SQ020',
        'text': 'You see two people arguing loudly. You:',
        'options': {
            'A': 'Walk away',
            'B': 'Try to calmly mediate if safe',
            'C': 'Take sides',
            'D': 'Call security',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 3},
        'factor': 'social_cognising',
        'explain': 'High SQ can de-escalate conflict.',
        'min_age': 15,
    },
]

# ========================
#  AQ QUESTIONS (20, CORE dimensions)
# ========================

AQ_QUESTIONS = [
    {
        'id': 'AQ001',
        'text': 'When something bad happens, you believe:',
        'options': {
            'A': 'It was totally out of my control',
            'B': 'I had some role and can influence the outcome',
            'C': 'It\'s always someone else\'s fault',
            'D': 'These things just happen randomly',
        },
        'scores': {'A': 3, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'Control',
        'explain': 'High AQ: believe you have agency, even in adversity.',
        'min_age': 12,
    },
    {
        'id': 'AQ002',
        'text': 'A project fails. How far does it affect your mindset?',
        'options': {
            'A': 'I question my entire career',
            'B': 'I feel bad about this project, nothing more',
            'C': 'It doesn\'t affect me',
            'D': 'I blame the team',
        },
        'scores': {'A': 1, 'B': 5, 'C': 3, 'D': 2},
        'dimension': 'Reach',
        'explain': 'High AQ: limit how far adversity bleeds into other areas.',
        'min_age': 14,
    },
    {
        'id': 'AQ003',
        'text': 'Facing a hard challenge, you:',
        'options': {
            'A': 'Give up if it takes too long',
            'B': 'Keep trying while adjusting your approach',
            'C': 'Push through the same way until it works',
            'D': 'Ask someone else to do it',
        },
        'scores': {'A': 1, 'B': 5, 'C': 3, 'D': 2},
        'dimension': 'Endurance',
        'explain': 'High AQ: persistent AND flexible.',
        'min_age': 13,
    },
    {
        'id': 'AQ004',
        'text': 'Your business fails. In your head, you think:',
        'options': {
            'A': 'I am a complete failure',
            'B': 'The market wasn\'t right for this',
            'C': 'I made some mistakes I can learn from',
            'D': 'My partners let me down',
        },
        'scores': {'A': 1, 'B': 3, 'C': 5, 'D': 2},
        'dimension': 'Ownership',
        'explain': 'High AQ: own your part without blaming yourself entirely.',
        'min_age': 15,
    },
    {
        'id': 'AQ005',
        'text': 'Stuck in a situation you can\'t change, you:',
        'options': {
            'A': 'Get frustrated',
            'B': 'Use the time productively or reframe',
            'C': 'Feel numb about it',
            'D': 'Complain',
        },
        'scores': {'A': 1, 'B': 5, 'C': 3, 'D': 1},
        'dimension': 'Control',
        'explain': 'Focus on what you CAN control.',
        'min_age': 12,
    },
    {
        'id': 'AQ006',
        'text': 'You fail a test you studied hard for. Next:',
        'options': {
            'A': 'Studying doesn\'t work for me',
            'B': 'Figure out what went wrong and study smarter',
            'C': 'Hope nobody asks about it',
            'D': 'Ask to retake it',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 2},
        'dimension': 'Ownership',
        'explain': 'Bounce back with adjusted strategy.',
        'min_age': 11,
    },
    {
        'id': 'AQ007',
        'text': 'You lose your job. How long do you feel it will affect your life?',
        'options': {
            'A': 'A few days',
            'B': 'A few weeks',
            'C': 'Months',
            'D': 'Years or forever',
        },
        'scores': {'A': 5, 'B': 4, 'C': 2, 'D': 1},
        'dimension': 'Endurance',
        'explain': 'High AQ: adversity is temporary.',
        'min_age': 16,
    },
    {
        'id': 'AQ008',
        'text': 'A relationship ends badly. You tend to:',
        'options': {
            'A': 'Blame the other person completely',
            'B': 'Blame yourself completely',
            'C': 'Learn from it and move on',
            'D': 'Avoid relationships for a long time',
        },
        'scores': {'A': 2, 'B': 2, 'C': 5, 'D': 1},
        'dimension': 'Ownership',
        'explain': 'High AQ: extract lessons without wallowing.',
        'min_age': 15,
    },
    {
        'id': 'AQ009',
        'text': 'When criticism comes, you:',
        'options': {
            'A': 'Take it as a personal attack',
            'B': 'Consider if it\'s useful, discard if not',
            'C': 'Agree to avoid conflict',
            'D': 'Criticise back',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 1},
        'dimension': 'Control',
        'explain': 'High AQ: filter feedback rationally.',
        'min_age': 13,
    },
    {
        'id': 'AQ010',
        'text': 'One bad event at the start of your day usually:',
        'options': {
            'A': 'Ruins the whole day',
            'B': 'Affects a few hours',
            'C': 'I forget it quickly',
            'D': 'I use it as motivation',
        },
        'scores': {'A': 1, 'B': 3, 'C': 4, 'D': 5},
        'dimension': 'Reach',
        'explain': 'High AQ: contain the damage.',
        'min_age': 12,
    },
    {
        'id': 'AQ011',
        'text': 'You face a repeated obstacle. You:',
        'options': {
            'A': 'Try the same method harder',
            'B': 'Change approach after a few tries',
            'C': 'Give up',
            'D': 'Ask someone else to solve it',
        },
        'scores': {'A': 2, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'Endurance',
        'explain': 'Adaptability + persistence = high AQ.',
        'min_age': 14,
    },
    {
        'id': 'AQ012',
        'text': 'After a setback, how quickly do you take action to improve?',
        'options': {
            'A': 'Immediately',
            'B': 'Within a day',
            'C': 'Within a week',
            'D': 'I often stay stuck',
        },
        'scores': {'A': 5, 'B': 4, 'C': 2, 'D': 1},
        'dimension': 'Ownership',
        'explain': 'High AQ: swift ownership and action.',
        'min_age': 13,
    },
    # New AQ questions
    {
        'id': 'AQ013',
        'text': 'You’re passed over for a promotion. You:',
        'options': {
            'A': 'Ask for feedback and work on weaknesses',
            'B': 'Assume the boss doesn’t like you',
            'C': 'Quit',
            'D': 'Stop trying',
        },
        'scores': {'A': 5, 'B': 2, 'C': 1, 'D': 1},
        'dimension': 'Ownership',
        'explain': 'Seek constructive feedback to improve.',
        'min_age': 16,
    },
    {
        'id': 'AQ014',
        'text': 'You try something new and fail. You think:',
        'options': {
            'A': 'I’m just not good at this',
            'B': 'That was one attempt, I’ll try differently',
            'C': 'It’s a waste of time',
            'D': 'Others made it look easy',
        },
        'scores': {'A': 1, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'Endurance',
        'explain': 'Growth mindset fuels resilience.',
        'min_age': 12,
    },
    {
        'id': 'AQ015',
        'text': 'Unexpected expense hits your budget. You:',
        'options': {
            'A': 'Panic and give up on saving',
            'B': 'Adjust other spending and keep going',
            'C': 'Borrow money without a plan',
            'D': 'Blame the situation',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 2},
        'dimension': 'Control',
        'explain': 'Focus on what you can control.',
        'min_age': 14,
    },
    {
        'id': 'AQ016',
        'text': 'Your team loses an important client. You:',
        'options': {
            'A': 'Blame the salesperson',
            'B': 'Analyse what went wrong as a team',
            'C': 'Feel hopeless about the company',
            'D': 'Ignore it and move on',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 1},
        'dimension': 'Ownership',
        'explain': 'Collective ownership builds resilience.',
        'min_age': 15,
    },
    {
        'id': 'AQ017',
        'text': 'You’re stuck in traffic and will be late. You:',
        'options': {
            'A': 'Fume and stress',
            'B': 'Accept it and inform the person you’re meeting',
            'C': 'Drive aggressively',
            'D': 'Blame the city planners',
        },
        'scores': {'A': 1, 'B': 5, 'C': 1, 'D': 2},
        'dimension': 'Control',
        'explain': 'Focus on what you can do now.',
        'min_age': 12,
    },
    {
        'id': 'AQ018',
        'text': 'You get negative feedback on a creative project. You:',
        'options': {
            'A': 'Give up on that style',
            'B': 'Look for specific points to improve',
            'C': 'Argue with the feedback',
            'D': 'Ignore it',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 1},
        'dimension': 'Endurance',
        'explain': 'Use criticism as data, not defeat.',
        'min_age': 13,
    },
    {
        'id': 'AQ019',
        'text': 'A natural disaster disrupts your plans. You:',
        'options': {
            'A': 'Feel victimised for weeks',
            'B': 'Make new plans quickly',
            'C': 'Blame the weather service',
            'D': 'Cancel everything indefinitely',
        },
        'scores': {'A': 1, 'B': 5, 'C': 2, 'D': 1},
        'dimension': 'Reach',
        'explain': 'High AQ: adapt and move forward.',
        'min_age': 14,
    },
    {
        'id': 'AQ020',
        'text': 'You lose a competition you trained hard for. You:',
        'options': {
            'A': 'Vow to never compete again',
            'B': 'Analyse your performance and train smarter',
            'C': 'Blame the judges',
            'D': 'Congratulate the winner and move on',
        },
        'scores': {'A': 1, 'B': 5, 'C': 1, 'D': 3},
        'dimension': 'Endurance',
        'explain': 'Resilience means learning from loss.',
        'min_age': 13,
    },
]


def get_questions(test_type, age):
    """
    Get questions for a test, filtered by age.
    Returns list of question dicts (randomised, up to 10).
    """
    if test_type == "IQ":
        questions = IQ_QUESTIONS
    elif test_type == "EQ":
        questions = EQ_QUESTIONS
    elif test_type == "SQ":
        questions = SQ_QUESTIONS
    elif test_type == "AQ":
        questions = AQ_QUESTIONS
    else:
        return []

    # Filter by age
    eligible = [q for q in questions if q.get('min_age', 0) <= age]

    # If still empty (e.g., age < all min_age), fallback to all questions
    if not eligible:
        eligible = questions[:]

    # Randomise and return up to 10
    random.shuffle(eligible)
    return eligible[:10]